# Generated by Django 5.2.1 on 2025-05-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementfield',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementfield',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
