# Generated by Django 5.2.1 on 2025-06-07 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='measurement_guides/')),
                ('field_type', models.CharField(choices=[('bool', 'Yes/No'), ('choice', 'Dropdown'), ('text', 'Text'), ('float', 'Decimal Number')], default='text', max_length=10)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated choices for dropdowns.', null=True)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladybug.pattern')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladybug.fabric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='required_options',
            field=models.ManyToManyField(related_name='patterns', to='ladybug.patternoption'),
        ),
    ]
