# Generated by Django 5.2.1 on 2025-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0004_patternoption_cart_pattern_required_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='measurements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
