# Generated by Django 5.2.1 on 2025-06-08 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0005_cart_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.category'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='size_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.sizechart'),
        ),
        migrations.CreateModel(
            name='SizeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='ladybug.sizechart')),
            ],
        ),
        migrations.CreateModel(
            name='SizeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ladybug.sizechart')),
            ],
        ),
        migrations.CreateModel(
            name='SizeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='ladybug.sizechart')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladybug.sizeparameter')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladybug.sizelabel')),
            ],
            options={
                'unique_together': {('chart', 'size', 'parameter')},
            },
        ),
    ]
