# Generated by Django 5.2.1 on 2025-06-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0009_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fabric',
            name='units_inStock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabric',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pattern',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pattern',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_inStock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
