# Generated by Django 5.2.1 on 2025-06-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0011_remove_profile_address_order_area_order_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('paid', 'Paid'), ('cashondelivery', 'Cash On Delivery')], default='failed', max_length=50),
        ),
    ]
