# Generated by Django 5.2.1 on 2025-06-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0012_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('return_exchange_policy', models.TextField(blank=True, null=True)),
                ('manufacturing_info', models.TextField(blank=True, null=True)),
                ('highlights', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='Common_iformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.commoninformation'),
        ),
        migrations.AddField(
            model_name='product',
            name='Common_iformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.commoninformation'),
        ),
    ]
