# Generated by Django 5.2.1 on 2025-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0013_commoninformation_fabric_common_iformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
