# Generated by Django 5.2.1 on 2025-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0014_fabric_discount_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
