# Generated by Django 5.2.1 on 2025-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0015_product_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
