# Generated by Django 5.2.1 on 2025-06-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0016_remove_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='required_measurements',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='ladybug.measurementfield'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.sizechart'),
        ),
    ]
