# Generated by Django 5.2.1 on 2025-06-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0017_product_required_measurements_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
