# Generated by Django 5.2.1 on 2025-06-13 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0019_alter_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='review_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='required_measurements',
            field=models.ManyToManyField(blank=True, related_name='products', to='ladybug.measurementfield'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_token', models.CharField(max_length=100, unique=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.fabric')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladybug.order')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.pattern')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.product')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.profile')),
            ],
        ),
    ]
