# Generated by Django 5.2.1 on 2025-06-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0020_order_delivered_order_review_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
