# Generated by Django 5.2.1 on 2025-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0022_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('addional_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='fabrics', to='ladybug.tag'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='patterns', to='ladybug.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='products', to='ladybug.tag'),
        ),
    ]
