# Generated by Django 5.2.1 on 2025-06-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0023_cardimages_tag_fabric_tag_pattern_tag_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='addional_discount',
            new_name='additional_discount',
        ),
    ]
