# Generated by Django 5.2.1 on 2025-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0024_rename_addional_discount_tag_additional_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='additional_discount',
            new_name='additional_perc_discount',
        ),
        migrations.AddField(
            model_name='tag',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
