# Generated by Django 5.2.1 on 2025-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0026_sitehit_fabric_views_pattern_views_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='arrange_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='own_fabric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='arrange_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='own_fabric',
            field=models.BooleanField(default=False),
        ),
    ]
