# Generated by Django 5.2.1 on 2025-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0027_cart_arrange_pickup_cart_own_fabric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimages',
            name='name',
            field=models.CharField(choices=[('own_fabric', 'own_fabric'), ('purchase_fabric', 'purchase_fabric'), ('pickup', 'pickup'), ('drop', 'drop'), ('create_style_card', 'create_style_card')], default='create_style_card', max_length=50),
        ),
    ]
