# Generated by Django 5.2.1 on 2025-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0030_wallettransaction_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='discount',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='pattern',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
