# Generated by Django 5.2.1 on 2025-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0031_rename_discount_fabric_original_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_amount',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
