# Generated by Django 5.2.1 on 2025-06-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0032_rename_total_amount_cart_original_price_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladybug.fabriccategory'),
        ),
    ]
