# Generated by Django 5.2.1 on 2025-06-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0034_productimage_media_type_productimage_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
