# Generated by Django 5.2.1 on 2025-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybug', '0035_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_pattern_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_style_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
